version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    networks:
      - jellyfin
    ports:
      - 80:8096
    volumes:
      - config:/config
      - cache:/cache
      - /location/of/your/libray:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
volumes:
  cache:
  config:
networks:
  jellyfin:
